name: myapp1

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: build&push
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build -t myapp ./myapp
          docker tag myapp $DOCKER_USERNAME/myapp:latest
          docker push $DOCKER_USERNAME/myapp:latest

      - name: sshsetup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" | base64 -d  > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 64.188.65.35 >> ~/.ssh/known_hosts

      - name: ssh debug
        run: |
          ssh-keygen -y -f ~/.ssh/id_ed25519

      - name: deploy to vps
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        
        run: |
          ssh root@64.188.65.35 "
            docker pull $DOCKER_USERNAME/myapp:latest &&
            docker stop myapp || true &&
            docker rm myapp || true &&
            docker run -d --name myapp -p 8080:8080 $DOCKER_USERNAME/myapp:latest
          "
